on:
  push:
    tags: ["v1.0.0"]

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v1.0.0')
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm i -g --force corepack && corepack enable

      - name: Install Node.js, NPM and PNPM
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install

      - name: Release Electron app for macOS
        uses: imokhles/localizable-reader/@v1.0.0
        with:
          package_manager: "pnpm"
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: true
